# Generated by Django 3.0.8 on 2020-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.IntegerField()),
                ('s_city', models.CharField(max_length=100)),
                ('d_city', models.CharField(max_length=100)),
                ('time_1', models.DateField()),
                ('time_2', models.DateField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('famly_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'fem'), ('Male', 'ma')], max_length=10)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('flight', models.ManyToManyField(to='index.Flight')),
            ],
        ),
    ]
