# Generated by Django 3.0.8 on 2020-07-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_ticket_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='contract_df_ate',
            new_name='contract_d_ate',
        ),
    ]
