# Generated by Django 3.0.8 on 2020-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200705_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airplane',
            new_name='AirCraft',
        ),
        migrations.AlterField(
            model_name='crew',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
