# Generated by Django 3.0.8 on 2020-07-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200707_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='gender',
        ),
    ]
