# Generated by Django 3.0.8 on 2020-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_crew_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='famly_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
