# Generated by Django 3.0.8 on 2020-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20200708_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='agency',
            field=models.ManyToManyField(null=True, to='index.Agency'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airplane',
            field=models.ManyToManyField(null=True, to='index.Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ManyToManyField(null=True, to='index.Aircraft'),
        ),
    ]
